using module .\Classes\CompletionHelper.psm1
using namespace System

$InterfaceAliasCommands = @(
    'Get-DnsClient'
    'Get-DnsClientServerAddress'
    'Get-NetConnectionProfile'
    'Get-NetIPAddress'
    'Get-NetIPConfiguration'
    'Get-NetIPInterface'
    'Get-NetNeighbor'
    'Get-NetRoute'
    'New-NetFirewallRule'
    'New-NetIPAddress'
    'New-NetIPsecRule'
    'New-NetNeighbor'
    'New-NetRoute'
    'New-SmbMultichannelConstraint'
    'Remove-NetIPAddress'
    'Remove-NetNeighbor'
    'Remove-NetRoute'
    'Remove-SmbMultichannelConstraint'
    'Set-DhcpServerv4Binding'
    'Set-DhcpServerv6Binding'
    'Set-DnsClient'
    'Set-DnsClientServerAddress'
    'Set-NetConnectionProfile'
    'Set-NetFirewallInterfaceFilter'
    'Set-NetFirewallRule'
    'Set-NetIPAddress'
    'Set-NetIPConfiguration'
    'Set-NetIPInterface'
    'Set-NetIPsecRule'
    'Set-NetNeighbor'
    'Set-NetRoute'
)
$NameCommands = @(
    'Add-NetLbfoTeamMember'
    'Add-NetLbfoTeamNic'
    'Disable-NetAdapter'
    'Disable-NetAdapterBinding'
    'Disable-NetAdapterChecksumOffload'
    'Disable-NetAdapterEncapsulatedPacketTaskOffload'
    'Disable-NetAdapterIPsecOffload'
    'Disable-NetAdapterLso'
    'Disable-NetAdapterPacketDirect'
    'Disable-NetAdapterPowerManagement'
    'Disable-NetAdapterQos'
    'Disable-NetAdapterRdma'
    'Disable-NetAdapterRsc'
    'Disable-NetAdapterRss'
    'Disable-NetAdapterSriov'
    'Disable-NetAdapterUso'
    'Disable-NetAdapterVmq'
    'Enable-NetAdapter'
    'Enable-NetAdapterBinding'
    'Enable-NetAdapterChecksumOffload'
    'Enable-NetAdapterEncapsulatedPacketTaskOffload'
    'Enable-NetAdapterIPsecOffload'
    'Enable-NetAdapterLso'
    'Enable-NetAdapterPacketDirect'
    'Enable-NetAdapterPowerManagement'
    'Enable-NetAdapterQos'
    'Enable-NetAdapterRdma'
    'Enable-NetAdapterRsc'
    'Enable-NetAdapterRss'
    'Enable-NetAdapterSriov'
    'Enable-NetAdapterUso'
    'Enable-NetAdapterVmq'
    'Get-NetAdapter'
    'Get-NetAdapterAdvancedProperty'
    'Get-NetAdapterBinding'
    'Get-NetAdapterChecksumOffload'
    'Get-NetAdapterEncapsulatedPacketTaskOffload'
    'Get-NetAdapterHardwareInfo'
    'Get-NetAdapterIPsecOffload'
    'Get-NetAdapterLso'
    'Get-NetAdapterPacketDirect'
    'Get-NetAdapterPowerManagement'
    'Get-NetAdapterQos'
    'Get-NetAdapterRdma'
    'Get-NetAdapterRsc'
    'Get-NetAdapterRss'
    'Get-NetAdapterSriov'
    'Get-NetAdapterSriovVf'
    'Get-NetAdapterStatistics'
    'Get-NetAdapterUso'
    'Get-NetAdapterVmq'
    'Get-NetAdapterVmqQueue'
    'Get-NetAdapterVPort'
    'Get-NetLbfoTeamMember'
    'Get-NetLbfoTeamNic'
    'New-NetAdapterAdvancedProperty'
    'Remove-NetAdapterAdvancedProperty'
    'Remove-NetLbfoTeamMember'
    'Rename-NetAdapter'
    'Reset-NetAdapterAdvancedProperty'
    'Restart-NetAdapter'
    'Set-NetAdapter'
    'Set-NetAdapterAdvancedProperty'
    'Set-NetAdapterBinding'
    'Set-NetAdapterChecksumOffload'
    'Set-NetAdapterEncapsulatedPacketTaskOffload'
    'Set-NetAdapterIPsecOffload'
    'Set-NetAdapterLso'
    'Set-NetAdapterPacketDirect'
    'Set-NetAdapterPowerManagement'
    'Set-NetAdapterQos'
    'Set-NetAdapterRdma'
    'Set-NetAdapterRsc'
    'Set-NetAdapterRss'
    'Set-NetAdapterSriov'
    'Set-NetAdapterUso'
    'Set-NetAdapterVmq'
    'Set-NetLbfoTeamMember'
    'Set-NetLbfoTeamNic'
)
$ScriptBlock = {
    param($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameters)
    $TrimmedWord = [CompletionHelper]::TrimQuotes($wordToComplete)

    foreach ($Adapter in [CompletionHelper]::GetCachedResults("Get-NetAdapter", $false))
    {
        if ($Adapter.Name.StartsWith($TrimmedWord, [StringComparison]::OrdinalIgnoreCase))
        {
            [CompletionHelper]::NewParamCompletionResult($Adapter.Name, $Adapter.InterfaceDescription)
        }
    }
}
Register-ArgumentCompleter -CommandName $InterfaceAliasCommands -ParameterName InterfaceAlias -ScriptBlock $ScriptBlock
Register-ArgumentCompleter -CommandName $NameCommands -ParameterName Name -ScriptBlock $ScriptBlock